import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Form from '../components/form'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Link Sharer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Link Sharer!</a>
        </h1>

        <h3>
          Share a link through Telegram using <code className={styles.code}>LinkSharer_bot</code>.
        </h3>
        <div className={styles.form}>
          <div className={styles.card}>
            <Form></Form>
          </div>
          
        </div>
        

        
          
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
